# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aeEchSROluJPIyNzSgk0yIWQlVdqyOsk
"""

a = int(input("Nhập vào số a: "))
    b = int(input("Nhập vào số b: "))

    Tong = a + b
    Hieu = a-b
    Thuong = a/b
    Tich = a*b

    print(f"Tổng {a} và {b}:", Tong)
    print(f"Hiệu {a} và {b}:", Hieu)
    print(f"Tích {a} và {b}:", Tich)
    print(f"Thương {a} và {b}:", Thuong)

s = "Hello World"
    result = s[2:5]
    print(result)

s = " Hello World "

    s1 = s.strip()

    upper = s.upper()

    lower = s.lower()

    result = s.replace("H", "J")

    print(s1)
    print(upper)
    print(lower)
    print(result)

a = int(input("Nhập vào số a: "))
    b = int(input("Nhập vào số b: "))
    s = "Hello World"

    if a > b:
      print(s)
    else:
      print(f"{a} không lớn hơn {b}")

a = int(input("Nhập vào số a: "))
    b = int(input("Nhập vào số b: "))

    if a == b:
      print("Yes")
    else:
      print("No")

a = int(input("Nhập vào số a: "))
    b = int(input("Nhập vào số b: "))

    if a > b:
        print("2")
    elif a == b:
      print("1")
    else:
      print("3")

a = int(input("Nhập vào số a: "))
    b = int(input("Nhập vào số b: "))
    d = int(input("Nhập vào số d: "))
    s = "Hello World"

    if a == b and b == d:
      print(s)
    else:
      print("Em lười viết")

a = int(input("Nhập vào số a: "))
    b = int(input("Nhập vào số b: "))
    d = int(input("Nhập vào số d: "))
    c = int(input("Nhập vào số c: "))
    s = "Hello World"

    if a == b or c == d:
      print(s)
    else:
      print("Em lười viết")

a = int(input("Nhập vào số a: "))
    b = int(input("Nhập vào số b: "))

    print("Yes") if a > b else print("No")

a = int(input("Nhập vào số a: "))
    b = int(input("Nhập vào số b: "))

    print("A") if a > b else print("=") if a == b else print("B")

n = int(input("Nhập vào n: "))

    a = []

    for i in range(n):
        x = int(input(f"a[{i+1}] = "))
        a.append(x)

    b = [x for x in a if x % 2 == 0]

    print("Mảng a: ", a)
    print("Mảng b (chứa phần tử chẵn của a): ",b)

tong = 0

    for i in range(1000):
        if i % 3 == 0 and i % 5 == 0:
            tong += i

    print("Tổng: ", tong)

def tron_mang(a, b):
    c = []
    n = min(len(a), len(b))

    for i in range(n):
        c.append(a[i] + b[i])

    if len(a) > len(b):
        c.extend(a[n:])
    else:
        c.extend(b[n:])

    return c

a = [3, 9, 1, 4]
b = [2, 7, 4, 3, 2, 8]

kq = tron_mang(a, b)
print("Mảng a: ", a)
print("Mảng b: ", b)
print("Kết quả: ", kq)

import random
# a. Tạo mảng ngẫu nhiên
def tao_mang(m, n):
    return [[random.randint(0, 100) for _ in range(n)] for _ in range(m)]

# b. Xuất dòng k
def xuat_dong(a, k):
    print(a[k])

# c. Xuất cột k
def xuat_cot(a, k):
    for row in a:
        print(row[k], end=" ")
    print()

# d. Dòng có tổng > 45 lớn nhất
def dong_max_lon_hon_45(a):
    max_sum = -1
    index = -1
    for i in range(len(a)):
        s = sum(a[i])
        if s > 45 and s > max_sum:
            max_sum = s
            index = i
    return index, max_sum

# e. Cột có tích nhỏ nhất
def cot_tich_nho_nhat(a):
    n = len(a[0])
    min_prod = None
    index = -1
    for j in range(n):
        prod = 1
        for i in range(len(a)):
            prod *= a[i][j]
        if min_prod is None or prod < min_prod:
            min_prod = prod
            index = j
    return index, min_prod

# f. Phần tử dòng chẵn, cột lẻ (index bắt đầu 0)
def dong_chan_cot_le(a):
    kq = []
    for i in range(0, len(a), 2):
        for j in range(1, len(a[0]), 2):
            kq.append(a[i][j])
    return kq

# g. TBC số chẵn thuộc dòng lẻ
def tbc_chan_dong_le(a):
    tong = dem = 0
    for i in range(1, len(a), 2):
        for x in a[i]:
            if x % 2 == 0:
                tong += x
                dem += 1
    return tong / dem if dem != 0 else 0

# h. TBC các phần tử biên
def tbc_bien(a):
    m, n = len(a), len(a[0])
    tong = dem = 0

    for i in range(m):
        for j in range(n):
            if i == 0 or i == m-1 or j == 0 or j == n-1:
                tong += a[i][j]
                dem += 1
    return tong / dem

# i. TBC tích phần tử không thuộc biên
def tbc_tich_noi(a):
    m, n = len(a), len(a[0])
    tich = 1
    dem = 0

    for i in range(1, m-1):
        for j in range(1, n-1):
            tich *= a[i][j]
            dem += 1

    return tich / dem if dem != 0 else 0

m, n = 4, 5
a = tao_mang(m, n)

print("Mảng a:")
for row in a:
    print(row)

xuat_dong(a, 1)
print("-----------")
xuat_cot(a, 2)

print("Dòng max >45:", dong_max_lon_hon_45(a))
print("Cột tích nhỏ nhất:", cot_tich_nho_nhat(a))
print("Dòng chẵn cột lẻ:", dong_chan_cot_le(a))
print("TBC chẵn dòng lẻ:", tbc_chan_dong_le(a))
print("TBC biên:", tbc_bien(a))
print("TBC không biên:", tbc_tich_noi(a))

#a.	Xây dựng cấu trúc SINHVIEN mô tả một sinh viên
class SinhVien:
    def __init__(self, masv, tensv, namsinh, dtb):
        self.masv = masv
        self.tensv = tensv
        self.namsinh = namsinh
        self.dtb = dtb

#b. Mảng n sinh viên
ds = [
    SinhVien("02DH0001", "Phan Thi Lan", 2004, 6.5),
    SinhVien("03CD0002", "Nguyen Van A", 2005, 4.2),
    SinhVien("02DH0003", "Tran Thi Lan", 2003, 7.0),
    SinhVien("02DH0004", "Phan Van B", 2002, 8.0)
]

#c. Sinh viên đủ điều kiện lên lớp
def sv_len_lop(ds):
    return sum(1 for sv in ds if sv.dtb >= 5)

#d. Xuất các sinh viên đủ 20 tuổi
def sv_du_tuoi(ds, nam_hien_tai):
    print("Sinh viên đủ 20 tuổi: ")

    for sv in ds:
        if nam_hien_tai - sv.namsinh >= 20:
            print(sv.tensv)

#e. Đếm số sinh viên hệ đại học
def sv_dh(ds):
    return sum(1 for sv in ds if sv.masv[2:4] == "DH")

#f. Đếm mảng chứa tên "Lan"
def dem_ten_lan(ds):
    return sum(1 for sv in ds if sv.tensv.split()[-1] == "Lan")

#f. Đếm mảng chứa học "Phan"
def dem_ho_phan(ds):
    return sum(1 for sv in ds if sv.tensv.split()[0] == "Phan")

#Danh sách sinh viên
def in_ds(ds):
    print("Danh sách sinh viên: ")
    for sv in ds:
        print(f"Mã SV: {sv.masv} | Tên: {sv.tensv} | Năm sinh: {sv.namsinh} | ĐTB: {sv.dtb}")

in_ds(ds)

print(f"Có {sv_len_lop(ds)} sinh viên lên lớp")

sv_du_tuoi(ds, 2026)

print(f"Có {sv_dh(ds)} sinh viên hệ 'Đại học'")

print(f"Có {dem_ten_lan(ds)} sinh viên tên 'Lan'")
print(f"Có {dem_ho_phan(ds)} sinh viên họ 'Phan'")